# info
name: Shane Logsdon
description: "I code things. Sometimes, I write about them here."
url: "http://shane.logsdon.io"

# rendering
markdown: kramdown
kramdown:
  input: GFM
pygments: true

# settings
permalink: /posts/:categories/:title
paginate: 6
paginate_path: "posts/page/:num"
encoding: "utf-8"