# info
name: Shane Logsdon
description: "I code things. Sometimes, I write about them here."
url: "http://shane.logsdon.io"

# rendering
markdown: redcarpet

# settings
permalink: /posts/:categories/:title
paginate: 5
paginate_path: "posts/page/:num"
encoding: "utf-8"