# info
name: Shane Logsdon
description: "I code things. Sometimes, I write about them here."
url: "http://shane.logsdon.io"

# rendering
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# settings
permalink: /:categories/:title
relative_permalinks: false
paginate: 5
paginate_path: "page/:num"
encoding: "utf-8"