db:
  extends:
    file: docker-compose.yml
    service: db

haproxy:
  image: tutum/haproxy
  ports:
    - "8000:80"
    - "443:443"
    - "1936:1936"
  links:
    - varnish

hhvm:
  image: "estebanmatias92/hhvm:fastcgi"
  command: "hhvm --mode server -vServer.Port=9000"
  expose: 
    - 9000
  links:
    - db
    - redis
  volumes:
    - ".:/code"
  environment:
    MYSQL_HOST: db
    REDIS_HOST: redis
    WP_ENV: production
    VARNISH_HOST: varnish

redis:
  extends:
    file: docker-compose.yml
    service: redis

web:
  build: docker-nginx-hhvm
  links:
    - hhvm
  volumes_from:
    - hhvm

varnish:
  image: million12/varnish
  links:
    - "web:backend-host"
  volumes_from:
    - web
  environment:
    VCL_CONFIG: /code/src/default.vcl
